version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install serverless -g 
      - npm install
  build:
    commands:
      - sls deploy function -f getMsg -r ap-northeast-1 -s dev
artifacts:
  files:
    - '**/*'
  base-directory: .serverless