version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install serverless -g 
      - npm install
  build:
    commands:
      - sls deploy -s dev -r ap-northeast-1
artifacts:
  files:
    - '**/*'
  base-directory: .serverless