version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install serverless -g 
      - npm install
  build:
    commands:
      - serverless deploy function --function serverless-nodejs-api-alpha-dev-getMsg
artifacts:
  files:
    - '**/*'
  base-directory: .serverless